CREATE TABLE resources (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                     BIGINT       NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP    NOT NULL DEFAULT now(),
    name                        VARCHAR(255) NOT NULL,
    description                 TEXT,
    category                    VARCHAR(100),
    slot_duration_minutes       INT          NOT NULL,
    cancellation_window_hours   INT          NOT NULL,
    active                      BOOLEAN      NOT NULL DEFAULT true,
    managed_by_user_id          BIGINT       NOT NULL REFERENCES users (id),

    CONSTRAINT ck_resources_slot_duration_positive CHECK (slot_duration_minutes > 0),
    CONSTRAINT ck_resources_cancellation_window_non_negative CHECK (cancellation_window_hours >= 0)
);

CREATE INDEX idx_resources_managed_by ON resources (managed_by_user_id);
CREATE INDEX idx_resources_active ON resources (active);

COMMENT ON TABLE resources IS 'Recurso reservable: cancha, consultorio, silla de salon, etc.';
COMMENT ON COLUMN resources.managed_by_user_id IS
    'Admin que administra este recurso. Seam de escalabilidad hacia una futura entidad Business/Organization.';
