CREATE TABLE availabilities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP   NOT NULL DEFAULT now(),
    resource_id   BIGINT      NOT NULL REFERENCES resources (id),
    day_of_week   VARCHAR(10) NOT NULL,
    start_time    TIME        NOT NULL,
    end_time      TIME        NOT NULL,
    active        BOOLEAN     NOT NULL DEFAULT true,

    CONSTRAINT ck_availabilities_day_of_week CHECK (
        day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    ),
    CONSTRAINT ck_availabilities_time_range CHECK (end_time > start_time)
);

CREATE INDEX idx_availabilities_resource_day ON availabilities (resource_id, day_of_week);

COMMENT ON TABLE availabilities IS
    'Regla de disponibilidad semanal recurrente de un resource (no representa fechas concretas).';
