CREATE TABLE reservations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               BIGINT      NOT NULL DEFAULT 0,
    created_at            TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP   NOT NULL DEFAULT now(),
    resource_id           BIGINT      NOT NULL REFERENCES resources (id),
    client_user_id        BIGINT      NOT NULL REFERENCES users (id),
    start_time            TIMESTAMP   NOT NULL,
    end_time              TIMESTAMP   NOT NULL,
    status                VARCHAR(20) NOT NULL,
    cancelled_at          TIMESTAMP,
    cancellation_reason   VARCHAR(500),

    CONSTRAINT ck_reservations_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT ck_reservations_time_range CHECK (end_time > start_time)
);

-- Red de seguridad anti-overbooking a nivel de BD: un mismo resource no puede
-- tener dos reservas activas (PENDING/CONFIRMED) que arranquen en el mismo
-- start_time. Es correcto y suficiente (no hace falta un exclusion constraint
-- por rango) porque los slots son de duracion fija por resource: dos
-- reservas del mismo resource jamas se solapan parcialmente, o coinciden
-- exactamente en start_time o no se tocan. El lock pesimista en la capa de
-- servicio evita la carrera antes del commit; este indice es la garantia
-- final a nivel de base de datos si esa capa fallara.
CREATE UNIQUE INDEX uq_reservations_active_slot
    ON reservations (resource_id, start_time)
    WHERE status IN ('PENDING', 'CONFIRMED');

CREATE INDEX idx_reservations_client ON reservations (client_user_id);
CREATE INDEX idx_reservations_resource_status ON reservations (resource_id, status);

COMMENT ON TABLE reservations IS 'Reserva de un slot concreto (fecha+hora) de un resource.';
